Fixed levelup sound not working
Since the import was missing I kept getting this exception on levelups:

 [SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/wcs/wcs.py", line 1138, in on_player_level_up
    if cfg_level_up_sound.get_int():
NameError: name 'cfg_level_up_sound' is not defined

This fixes the issue and now the sounds work. This has been tested on CSGO